#!/usr/bin/env python3
"""
Generate src/sim.local.html: index.html wrapped in a fake iCUE host environment.

Browser preview alone cannot catch host-integration bugs, because outside iCUE the bridge
takes a completely different boot path. This reproduces the real one:

  * tr() exists, so the widget believes it is inside iCUE
  * settings arrive as injected globals rather than URL parameters
  * colours arrive in Qt's serialisation, e.g. "rgb(1 1 1)" for white
  * iCUE_initialized is a LEXICAL global (const), so it is absent from window, and
    onICUEInitialized is never called

That last point is what made the widget render as static placeholders on the device while
looking perfect in preview. Any change to the boot path should be checked here.

  python3 tools/make-sim.py [--diagnostics]
  then open http://localhost:8123/src/sim.local.html
"""
import argparse
import pathlib
import sys

PREAMBLE = """
<!-- GENERATED by tools/make-sim.py. Gitignored. Fakes the iCUE host environment. -->
<script>
window.tr = function (key) {
  return new Promise(function (resolve) { setTimeout(function () { resolve(key); }, 30); });
};
window.iCUE = {
  iCUELanguage: "en",
  allTimeZones: function () { return []; },
  defaultTimeZone: function () { return "%(zone)s"; },
  default24HourFormat: function () { return "12h"; },
  isPreview: false
};
window.uniqueId = "sim-instance-1";

window.calendarUrl1 = "%(feed)s";
window.calendarUrl2 = "";
window.calendarUrl3 = "";
window.proxyBase = "http://localhost:8010";
window.agendaDays = 3;
window.refreshMinutes = 10;
window.weatherQuery = "%(place)s";
window.temperatureUnits = "\\u00b0F";
window.timeZone = "%(zone)s";
window.timeFormat = "12h";
window.showDiagnostics = %(diagnostics)s;

/* Qt's QColor serialisation, which is not CSS. */
window.textColor = "rgb(1 1 1)";
window.accentColor = "rgb(0.541176 0.705882 0.972549)";
window.accentColor2 = "rgb(0.917647 0.262745 0.207843)";
window.backgroundColor = "rgb(0.043137 0.050980 0.062745)";
window.transparency = 100;

/* Lexically scoped: absent from window. Reading it needs the bridge's hostValue(). */
const iCUE_initialized = true;
</script>
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--diagnostics", action="store_true", help="start with the readout visible")
    parser.add_argument("--port", type=int, default=8123)
    parser.add_argument("--place", default="02110")
    parser.add_argument("--zone", default="America/New_York")
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    source = root / "src" / "index.html"
    if not source.exists():
        sys.exit(f"error: {source} not found")

    values = {
        "zone": args.zone,
        "place": args.place,
        "feed": f"http://localhost:{args.port}/test/fixtures/busy.ics",
        "diagnostics": "true" if args.diagnostics else "false",
    }
    html = source.read_text(encoding="utf-8").replace("<head>", "<head>" + PREAMBLE % values, 1)

    target = root / "src" / "sim.local.html"
    target.write_text(html, encoding="utf-8")
    print(f"wrote {target.relative_to(root)}")
    print(f"open http://localhost:{args.port}/src/sim.local.html  (start the server with tools/preview.sh)")


if __name__ == "__main__":
    main()
